### ISSUE TITLE
Setup unit tests and integration tests for Sparkler

### ISSUE THREAD

**Issue by thammegowda** [USCDataScience/sparkler#32]
To begin with, write unit tests for : 
- test RDD functions 
- Test core functionality of plugins

## Tasks 
- [X] Setup a web server for testing 
  - [X] Bind it to junit to auto start and stop while running the tests
- [X] Setup a solr instance for testing
  - [X] Bind it to junit to auto start and stop
- [X] Test Default Fetcher
- [ ] Test Javascript Engine functionality
- [ ] Test URL filters
- [ ] Test Fetch Function
- [ ] Test Parse Function
- [ ] Test Seed Injection
- [ ] Test URL Normalizer
- [ ] Test HDFS persistance
- [ ] Test Kafka Output

PS: 
The current progress can be tracked on https://github.com/USCDataScience/sparkler/tree/unittests branch

**Comment by thammegowda** [comment]
## Tasks 
- [X] Setup a web server for testing 
  - [X] Bind it to junit to auto start and stop while running the tests
- [X] Setup a solr instance for testing
  - [X] Bind it to junit to auto start and stop
- [X] Test Default Fetcher
- [ ] Test Javascript Engine functionality
- [ ] Test URL filters
- [ ] Test Fetch Function
- [ ] Test Parse Function
- [ ] Test Seed Injection
- [ ] Test URL Normalizer
- [ ] Test HDFS persistance
- [ ] Test Kafka Output


The current progress can be tracked on https://github.com/USCDataScience/sparkler/tree/unittests branch
